### ISSUE TITLE
Route calculated through vs around Switzerland.

### ISSUE THREAD

**Issue by Polymnia** [julianrojas87/era-compatibility-check#32]
Some routes are expected to go through Switzerland but instead the route is calculated around.
Examples: 

1. Annweiler-Sarnstall --> ALBIZZATE SOLBIATE ARNO. 
2. Lyon-Perrache --> St.Anton am Arlberg

Please investigate if there is any issue with border points data.
![RCC1](https://user-images.githubusercontent.com/5465275/115736574-af31f300-a38b-11eb-9364-2b75e350e044.PNG)
![RCC2](https://user-images.githubusercontent.com/5465275/115736712-c96bd100-a38b-11eb-87ed-8035a893cbe6.PNG)

**Comment by julianrojas87** [comment]
After looking into this issue, I was able to conclude that it is caused due to Switzerland not having any border points. This can be confirmed with [this Search Form query](https://tinyurl.com/y22mmw9p) (also empty in the old RINF search form).

In a more strict sense, Switzerland does have some OPs right at the borders with its neighbors but they do not share the same UOPID as their foreign counterparts, which causes a disconnection of the topological network. For example this [French border point](http://data.europa.eu/949/functionalInfrastructure/operationalPoints/EU00134) and its [Swiss counter part](http://data.europa.eu/949/functionalInfrastructure/operationalPoints/CH04319) have different IDs and look like this in the map of the old RINF app:

![image](https://user-images.githubusercontent.com/4950659/138161122-65c5d246-3d47-40a9-a7b5-d6d303745612.png)

For this reason all the routes mentioned above go around Switzerland and not through it. Which is also the case in the old RINF navigation app. However in the case of the route [Bregenz (A) - Lindau (D)](https://data-interop.era.europa.eu/?compatibilityVehicleType&fromId=http%3A%2F%2Fdata.europa.eu%2F949%2FfunctionalInfrastructure%2FoperationalPoints%2FATBg&fromLat=47.5029728&fromLng=9.739551&maxRoutes=1&toId=http%3A%2F%2Fdata.europa.eu%2F949%2FfunctionalInfrastructure%2FoperationalPoints%2FDE%2520%2520MLI&toLat=47.544367&toLng=9.681027), the route can be calculated because the border points defined by [Germany](https://rinf.era.europa.eu/RINF/Search/ExtraInfoOP/4580528?versionID=368) and [Austria](https://rinf.era.europa.eu/RINF/Search/ExtraInfoOP/639662?versionID=528) share the same UOPID which causes that they [become one and the same](http://data.europa.eu/949/functionalInfrastructure/operationalPoints/EU00028) in the KG.
